routes/web.php
<?php
use App\Http\Controllers\RegisterController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth\login');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::get('register/gettpk/{id}','Auth\RegisterController@getTpk');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('user/gettpk/{id}', 'UserController@getTpk');
Route::post('user/store', 'UserController@store');
Route::get('user', 'UserController@index');
Route::get('user/create', 'UserController@create');

Route::resource('user', 'UserController');
Route::resource('pertanyaan', 'PertanyaanController');
Route::post('survei/create', 'SurveiController@FormSurvei');
Route::resource('survei', 'SurveiController');

app/Survei.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Survei extends Model
{
    protected $table = "survei";

    protected $fillable = ['nikes', 'nama', 'telepon', 'kodetpk'];
}

app/Http/Controllers/SurveiController.php
<?php

namespace App\Http\Controllers;
use DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Pertanyaan;
use App\Survei;
use App\DetailSurvei;

class SurveiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tpk = DB::table('tpk')->where('id', '=', Auth::user()->kodetpk)->first();
        return view('survei.index', compact('tpk'));
    }

    public function formSurvei(Request $request){
        Survei::create($request->all());

        $survey = DB::table('survei')->latest('id')->first();
        $tpk = DB::table('tpk')->where('id', '=', Auth::user()->kodetpk)->first();
        $pertanyaan = Pertanyaan::where('kodetpk', Auth::user()->kodetpk)
                                ->where('status', '=', 'Aktif')
                                ->paginate(10);
        return view('survei.create', compact('pertanyaan', 'tpk', 'survey'))
                ->with('i',(request()->input('page',1) -1)*10);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
               // $rating = new Rating;
    // $rating->rating = 4;
    // $rating->user_id = \Auth::id();
    // $food->ratings()->save($rating);
    $survei = new Survei;
    $survei->id_survei = \Auth::id();
    $survei->survei = $request->input('star');
    $pertanyaan = Pertanyaan::find($request->input('id'));
    $survei->pertanyaan()->save($survei);
    return response()->json(['survei' => $survey->survei]);
        
        return view('survei.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/survei/create.blade.php
@extends('layouts.newapp1')
@section('content')

<div class="container">
        <div class=" form-row">
            <div class="col-lg-12 text-left">
                <!-- <h3 class="dua">{{$tpk->namatpk}}</h3>
                <p class="tiga" >Halo {{$survey->nama}}</p> -->
            </div>
        </div>
        <br>

        @if ($errors->all())
            <div class="alert alert-danger">
                <strong>Whoops! </strong> Ada permasalahan inputanmu.<br>
                <ul>
                    @foreach ($errors as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
        <form action="{{route('survei.store')}}" method="post" enctype="multipart/form-data">
            @csrf
            @foreach ($pertanyaan as $p) 
            <div  class="container text-center">
            <p class="dua">{{++$i}}. {{$p->pertanyaan}}</p>
                <input type="hidden" name="id_pertanyaan" value="{{$p->id}}">
                <input type="hidden" name="id_survei" value="{{$survey->id}}">
                <span class="star-rating star-5 satu">
                    <input class="form-check-input" type="radio" name="rating{{$p->id}}"  value="1"><i></i>
                    <input class="form-check-input" type="radio" name="rating{{$p->id}}"  value="2"><i></i>
                    <input class="form-check-input" type="radio" name="rating{{$p->id}}"  value="3"><i></i>
                    <input class="form-check-input" type="radio" name="rating{{$p->id}}"  value="4"><i></i>
                    <input class="form-check-input" type="radio" name="rating{{$p->id}}"  value="5"><i></i>
                </span>
            </div>
        
            @endforeach
            <hr>
            <div class="form-group text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
  
    </div>

@endsection

resources/views/survei/index.blade.php
@extends('layouts.newapp')
@section('content')





    <section class="wellcome_area clearfix" id="home">
    <div class="container">
        <div class=" form-row">
            <div class="col-lg-12">
                <!-- <h3>Survey {{$tpk->namatpk}}</h3> -->
            </div>
        </div>
        <br>

        @if ($errors->all())
            <div class="alert alert-danger">
                <strong>Whoops! </strong> Ada permasalahan inputanmu.<br>
                <ul>
                    @foreach ($errors as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
        <form action="{{route('survei.create')}}" method="post" enctype="multipart/form-data">
            @csrf
            <div  class="container text-center">
            <input type="hidden"  name="kodetpk" class="form-control" value="{{ Auth::user()->kodetpk }}">
            <div class="form-group row">
                <label for="nikes" class="col-sm-2 col-form-label">Nikes</label>
                <div class="col-sm-4">
                    <input type="text"  name="nikes" class="form-control" id="nikes" placeholder="">
                </div>
            </div>
            <div class="form-group row">
                <label for="nama" class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-4">
                    <input type="text"  name="nama" class="form-control" id="nama" placeholder="" >
                </div>
            </div>
            <div class="form-group row">
                <label for="telepon" class="col-sm-2 col-form-label">Telepon</label>
                <div class="col-sm-4">
                    <input type="number" name="telepon" class="form-control" id="telepon" placeholder="" >
                </div>
            </div>
            
             <hr>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Isi Survei</button>
                </div>
                </div>
        </form>

    </div>
    </section>
@endsection