routes/web.php
<?php
use App\Http\Controllers\RegisterController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth\login');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::get('register/gettpk/{id}','Auth\RegisterController@getTpk');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('user/gettpk/{id}', 'UserController@getTpk');
Route::post('user/store', 'UserController@store');
Route::get('user', 'UserController@index');
Route::get('user/create', 'UserController@create');

Route::resource('user', 'UserController');
Route::resource('pertanyaan', 'PertanyaanController');
Route::post('survei/create', 'SurveiController@FormSurvei');
Route::resource('survei', 'SurveiController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'kodearea', 'kodetpk', 'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\User;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    //
    public function index(){

        $user = User::orderBy('id','asc')->paginate(50);
        return view('user.index', compact('user'))
                ->with('i',(request()->input('page',1) -1)*10);
    }

    public function create(Request $request)
    {
        $area = DB::table('area')->select('id','namaarea')->get();
        return view('user.create', compact('area'));
    }

    public function getTpk($id) 
    {
        $tpk = DB::table("tpk")->where("kodearea", $id)->pluck("namatpk","id");
        return json_encode($tpk);
    }

    protected function store(Request $data)
    {
        User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'kodearea' => $data['kodearea'],
            'kodetpk' => $data['kodetpk'],
            'role' => $data['role'],
            'password' => Hash::make($data['password']),
        ]);
        
        return redirect()->route('user.index')
                ->with('success','Data berhasil ditambahkan');
    }
}

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
<link rel="stylesheet" href="{{asset('css/app.css')}}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script> 
<div class="container">
        <div class=" form-row">
            <div class="col-lg-12">
                <h3 class="text-center">Tambah User</h3>
            </div>
        </div>
        <br>

        @if ($errors->all())
            <div class="alert alert-danger">
                <strong>Whoops! </strong> Ada permasalahan inputanmu.<br>
                <ul>
                    @foreach ($errors as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
        <form method="POST" action="/user/store">
            @csrf

            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                <div class="col-md-5">
                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                    @error('name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-5">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right">Area</label>
                            <div class="col-sm-5">
                                <select name="kodearea"class="form-control" required>
                                @foreach($area as $area)
                                    <option value="{{ $area->id }}">{{ $area->namaarea}}</option>
                                @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right">TPK</label>
                            <div class="col-sm-5">
                                <select name="kodetpk"class="form-control" required>
                                    <option value="">-Pilih-</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right">Role</label>
                            <div class="col-sm-5">
                                <select name="role"class="form-control" required>
                                    <option value=""></option>
                                    <option value="ADMIN">ADMIN</option>
                                    <option value="ADMIN PUSAT">ADMIN PUSAT</option>
                                    <option value="ADMIN AREA">ADMIN AREA</option>
                                    <option value="ADMIN TPK">ADMIN TPK</option>
                                    <option value="ADMIN SURVEY">ADMIN SURVEY</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-5">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-5">
                                <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-5 offset-md-4 ">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Register') }}
                                </button>
                            </div>
                        </div>
                    </form>

    </div>
    <script type="text/javascript">
        jQuery(document).ready(function ()
        {
                jQuery('select[name="kodearea"]').on('change',function(){
                var areaID = jQuery(this).val();
                if(areaID)
                {
                    jQuery.ajax({
                        url : '/user/gettpk/' +areaID,
                        type : "GET",
                        dataType : "json",
                        success:function(data)
                        {
                            console.log(data);
                            jQuery('select[name="kodetpk"]').empty();
                            jQuery.each(data, function(id, namatpk){
                            $('select[name="kodetpk"]').append('<option value="'+ id +'">'+ namatpk +'</option>');
                            });
                        }
                    });
                }
                else
                {
                    $('select[name="kodetpk"]').empty();
                }
                });
        });
        </script>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class=" form-row">
            <div class="col-lg-12">
                <h3>Edit Data User</h3>
            </div>
        </div>
        <br>

        @if ($errors->all())
            <div class="alert alert-danger">
                <strong>Whoops! </strong> Ada permasalahan inputanmu.<br>
                <ul>
                    @foreach ($errors as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
        <form action="{{route('user.update',$user->id)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <input type="hidden" name="name" class="form-control" value="{{$user->name}}" placeholder="">
            <div class="form-group row">
                <label for="name" class="col-sm-2 col-form-label">Nama</label>
                <div class="col-sm-10">
                    <input type="text" name="name"  class="form-control" id="user" value="{{$user->name}}" placeholder="">
                </div>
            </div>
            <input type="hidden" name="email" class="form-control" value="{{$user->email}}" placeholder="">
            <div class="form-group row">
                <label for="user" class="col-sm-2 col-form-label">Email</label>
                <div class="col-sm-10">
                    <input type="text" name="email"  class="form-control" id="user" value="{{$user->email}}" placeholder="">
                </div>
            </div>
            <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right">Area</label>
                            <div class="col-sm-6">
                                <select name="kodearea"class="form-control" required>
                                @foreach($area as $area)
                                    <option value="{{ $area->id }}">{{ $area->namaarea}}</option>
                                @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right">TPK</label>
                            <div class="col-sm-6">
                                <select name="kodetpk"class="form-control" required>
                                    <option value="">-Pilih-</option>
                                </select>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label class="col-md-4 col-form-label text-md-right">Role</label>
                            <div class="col-sm-6">
                                <select name="role"class="form-control" required>
                                    <option value="ADMIN">ADMIN</option>
                                    <option value="ADMIN PUSAT">ADMIN PUSAT</option>
                                    <option value="ADMIN AREA">ADMIN AREA</option>
                                    <option value="ADMIN TPK">ADMIN TPK</option>
                                </select>
                            </div>
                        </div>
            <div class="form-group row">
                <label for="status" class="col-sm-2 col-form-label">Status</label>
                <div class="col-sm-10">
                    <select id="status" name="status"class="form-control">
                        <option  {{$user->status == 'Aktif' ? 'Selected' : ''}} value="Aktif">Aktif</option>
                        <option  {{$user->status == 'Non Aktif' ? 'Selected' : ''}} value="Non Aktif">Non Aktif</option>
                    </select>
                </div>
            </div>
             <hr>
                <div class="form-group">
                    <a href="{{route('user.index')}}" class="btn btn-success">Kembali</a>
                    <button type="submit" class="btn btn-primary">Edit</button>
                </div>
        </form>

    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')
@section('content')
 
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h3>Daftar user</h3>
            </div>
        </div> 
        <br>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{$message}}</p>        
        </div>
    @endif

    <div class="form-row">
        <div class="form-group mb-2 mr-auto">
            <a class="btn btn-success" href="/user/create"> Tambah Data </a>
        </div>
        <div class="form-group mb-2 ml-auto">
            <input class="form-control" id="myInput" type="text" placeholder="Search.."><br>
        </div>
    </div>
    
    <table class="table table-striped" id="table" data-toggle="table">
      <thead>
        <tr>
            <th data-order='desc' data-sortable="true">No</th>
            <th data-order='desc' data-sortable="true">User</th>
            <!-- <th data-order='desc' data-sortable="true">Action</th> -->
        </tr>
      </thead>
      <tbody id="myTable">
        @foreach ($user as $p) 
            <tr>
                <td>{{++$i}}</td>
                <td>{{$p->email}}</td>
                
            </tr>
        @endforeach
        </tbody>
    </table>

    <br>
    Halaman : {{ $user->currentPage() }} <br/>
	Jumlah Data : {{ $user->total() }} <br/>
	Data Per Halaman : {{ $user->perPage() }} <br/>

    {!! $user->links() !!}
    </div>
    <script>
        $(document).ready(function(){
        $("#myInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
        });
    </script>

@endsection