routes/web.php
<?php
use App\Http\Controllers\RegisterController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth\login');
});

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::get('register/gettpk/{id}','Auth\RegisterController@getTpk');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('user/gettpk/{id}', 'UserController@getTpk');
Route::post('user/store', 'UserController@store');
Route::get('user', 'UserController@index');
Route::get('user/create', 'UserController@create');

Route::resource('user', 'UserController');
Route::resource('pertanyaan', 'PertanyaanController');
Route::post('survei/create', 'SurveiController@FormSurvei');
Route::resource('survei', 'SurveiController');

app/Pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pertanyaan extends Model
{
    //
    protected $table = "pertanyaan";

    protected $fillable = ['pertanyaan', 'status', 'kodetpk'];
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use DB;
use App\Pertanyaan;

class PertanyaanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tpk = DB::table('tpk')->where('id', '=', Auth::user()->kodetpk)->first();
        $pertanyaan = Pertanyaan::where('kodetpk', Auth::user()->kodetpk)
                                ->paginate(10);
        return view('pertanyaan.index',compact('pertanyaan', 'tpk'))
                ->with('i',(request()->input('page',1) -1)*10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pertanyaan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'pertanyaan' => 'required',
            'kodetpk' => 'required',
            'status' => 'required',
        ]);
        
        Pertanyaan::create($request->all());
        return redirect()->route('pertanyaan.index')
                         ->with('success','Data berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pertanyaan = Pertanyaan::find($id);
        return view('pertanyaan.edit', compact('pertanyaan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'pertanyaan' => 'required',
            'kodetpk' => 'required',
            'status' => 'required',
        ]);
        $pertanyaan = Pertanyaan::find($id);
        $pertanyaan->pertanyaan = $request->get('pertanyaan');
        $pertanyaan->kodetpk = $request->get('kodetpk');
        $pertanyaan->status = $request->get('status');
        $pertanyaan->save();
        return redirect()->route('pertanyaan.index')
                         ->with('success', 'Data berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pertanyaan = Pertanyaan::find($id);
        $pertanyaan->delete();
        return redirect()->route('pertanyaan.index')
                         ->with('success', 'Data berhasil dihapus');
    }
}

resources/views/pertanyaan/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class=" form-row">
            <div class="col-lg-12">
                <h3>Tambah Data Pertanyaan</h3>
            </div>
        </div>
        <br>

        @if ($errors->all())
            <div class="alert alert-danger">
                <strong>Whoops! </strong> Ada permasalahan inputanmu.<br>
                <ul>
                    @foreach ($errors as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
        <form action="{{route('pertanyaan.store')}}" method="post" enctype="multipart/form-data">
            @csrf
            
            <div class="form-group row">
                <div class="col-sm-10">
                    <input type="hidden" value="{{ Auth::user()->kodetpk }}" name="kodetpk" class="form-control" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="pertanyaan" class="col-sm-2 col-form-label">Pertanyaan</label>
                <div class="col-sm-10">
                    <textarea class="form-control" name="pertanyaan" rows="2" cols="80" required></textarea>
                </div>
            </div>
            <div class="form-group row">
                <label for="status" class="col-sm-2 col-form-label">Status</label>
                <div class="col-sm-10">
                    <select id="status" name="status"class="form-control" required>
                        <option value="Aktif">Aktif</option>
                        <option value="Non Aktif">Non Aktif</option>
                    </select>
                </div>
            </div>
             <hr>
                <div class="form-group">
                    <a href="{{route('pertanyaan.index')}}" class="btn btn-success">Kembali</a>
                    <button type="submit" class="btn btn-primary">Tambah</button>
                </div>
        </form>

    </div>
    
@endsection

resources/views/pertanyaan/edit.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <div class=" form-row">
            <div class="col-lg-12">
                <h3>Edit Data Pertanyaan</h3>
            </div>
        </div>
        <br>

        @if ($errors->all())
            <div class="alert alert-danger">
                <strong>Whoops! </strong> Ada permasalahan inputanmu.<br>
                <ul>
                    @foreach ($errors as $error)
                        <li>{{$error}}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        
        <form action="{{route('pertanyaan.update',$pertanyaan->id)}}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <input type="hidden" name="kodetpk" class="form-control" value="{{$pertanyaan->kodetpk}}" placeholder="">
            <div class="form-group row">
                <label for="pertanyaan" class="col-sm-2 col-form-label">Pertanyaan</label>
                <div class="col-sm-10">
                    <input type="text" name="pertanyaan"  class="form-control" id="pertanyaan" value="{{$pertanyaan->pertanyaan}}" placeholder="">
                </div>
            </div>
            <div class="form-group row">
                <label for="status" class="col-sm-2 col-form-label">Status</label>
                <div class="col-sm-10">
                    <select id="status" name="status"class="form-control">
                        <option  {{$pertanyaan->status == 'Aktif' ? 'Selected' : ''}} value="Aktif">Aktif</option>
                        <option  {{$pertanyaan->status == 'Non Aktif' ? 'Selected' : ''}} value="Non Aktif">Non Aktif</option>
                    </select>
                </div>
            </div>
             <hr>
                <div class="form-group">
                    <a href="{{route('pertanyaan.index')}}" class="btn btn-success">Kembali</a>
                    <button type="submit" class="btn btn-primary">Edit</button>
                </div>
        </form>

    </div>
@endsection

resources/views/pertanyaan/index.blade.php
@extends('layouts.app')
@section('content')
 
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <h3>Daftar Pertanyaan {{$tpk->namatpk}}</h3>
            </div>
        </div> 
        <br>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{$message}}</p>        
        </div>
    @endif

    <div class="form-row">
        <div class="form-group mb-2 mr-auto">
            <a class="btn btn-success" href="{{ route('pertanyaan.create')}}"> Tambah Data </a>
        </div>
        <div class="form-group mb-2 ml-auto">
            <input class="form-control" id="myInput" type="text" placeholder="Search.."><br>
        </div>
    </div>
    
    <table class="table table-striped" id="table" data-toggle="table">
      <thead>
        <tr>
            <th data-order='desc' data-sortable="true">No</th>
            <th data-order='desc' data-sortable="true">Pertanyaan</th>
            <th data-order='desc' data-sortable="true">Status</th>
            <th data-order='desc' data-sortable="true">Action</th>
        </tr>
      </thead>
      <tbody id="myTable">
        @foreach ($pertanyaan as $p) 
            <tr>
                <td>{{++$i}}</td>
                <td>{{$p->pertanyaan}}</td>
                <td>{{$p->status}}</td>
                <td>
                    <form action="{{ route('pertanyaan.destroy',$p->id) }}" method="post">
                    <a class="btn btn-sm btn-success" href="{{ route('pertanyaan.show', $p->id)}}">Show</a>
                    <a class="btn btn-sm btn-warning" href="{{ route('pertanyaan.edit', $p->id)}}">Edit</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>    
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    <br>
    Halaman : {{ $pertanyaan->currentPage() }} <br/>
	Jumlah Data : {{ $pertanyaan->total() }} <br/>
	Data Per Halaman : {{ $pertanyaan->perPage() }} <br/>

    {!! $pertanyaan->links() !!}
    </div>
    <script>
        $(document).ready(function(){
        $("#myInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function() {
            $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
        });
    </script>

@endsection